#! /bin/bash
UtilSrc=("DCT.cpp" "Stats.cpp" "Tuning.cpp" "Waveforms.cpp")
ProcSrc=("ProcessData.cpp" "DataModels.cpp" "ModelInstances.cpp")

Path="/mnt/e/Projects/Scribe/src/"
UtilPath=""
MidiPath=""
ProcPath=""

Src=""
Headers=""

for s in ${UtilSrc[@]}; do
  Src+="../"${UtilPath}${s}" "
done

for s in ${ProcSrc[@]}; do
  Src+="../"${ProcPath}${s}" "
done


g++  -I "../" -o test.o Test.cpp Debug.cpp -ggdb ${Src}
